### ISSUE TITLE
How to set environment?

### ISSUE THREAD

**Issue by drsdre** [zand3rs/sails-test-helper#9]
How can I specify which environment configuration should be used before test are executed?

The environment configs are stored in config/env/development.js for example.

**Comment by zand3rs** [comment]
Technically you can but not advisable. You have to put the test specific settings in config/env/test.js since by default, the tests are executed on a test environment.

You can edit the Makefile and modify the ff. variable if you really want to execute the tests on a different environment:

ENV_VARS=NODE_ENV=test PORT=9999
